name: build arm64 bun

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 1"
  push:
    branches:
      - main
    paths:
      - ./bun/**
      
jobs:
  push:
    name: "arm64-pterodactyl-images-bun"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-qemu-action@v1
      - uses: docker/setup-buildx-action@v1
      - uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - uses: docker/build-push-action@v2
        with:
          context: ./bun
          file: ./bun/Dockerfile
          platforms: linux/arm64
          push: true
          tags: |
            viruslauncher/arm64-pterodactyl-images:bun
